# Generated by Django 5.0.6 on 2024-05-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='uploads/'),
        ),
    ]
